
TIMESERIES_NAME="ruuvi-sensors"

BASIC_AUTH_FORCE=False
BASIC_AUTH_USERNAME='user'
BASIC_AUTH_PASSWORD='pass'

# INFLUXDB PARAMETERS
# INFLUX_DB_NAME="ruuvi"
# INFLUX_URL=
# INFLUX_PORT=
# INFLUX_USER=
# INFLUX_PASSWORD=